### ISSUE TITLE
There's a mistake when you search for something.

### ISSUE THREAD

**Issue by xuad** [OMOSde/contao-om-search#1]
There's a mistake when you search for something. Contao Version 4.7.

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "The "contao_om_search.listener.customize_search" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead."`

The solution is to set the contao_om_search.listener.customize_search service to public (contao-om-search/src/Resources/config/listener.yml), or use DI to request the service.

**Comment by OMOSde** [comment]
Thx. Fixed in 108cdf5a07b31592d90424b91b16205e7d2163d9
